default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "gitlab actions testTests", 
    	clean: true,               
    	devices: ["iPhone 15"], 
    	fail_build: true 
    )
  end
end

