default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "gitlab actions testTests", 
      clean: true,
      destination: "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0"
    )
  end
end

