name: iOS Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean Derived Data
        run: xcrun simctl shutdown all && rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0  # Версия Ruby, которую использует Fastlane

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Fastlane
        run: bundle exec fastlane --version

      - name: Run unit tests without simulator
        run: bundle exec fastlane test

