name: iOS Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Fastlane
        run: bundle exec fastlane --version

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Boot iPhone 15 Simulator
        run: xcrun simctl boot "iPhone 15" || echo "Simulator already booted"

      - name: Run unit tests
        run: bundle exec fastlane test  
