name: iOS Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Версия Ruby, которую использует Fastlane

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install
        working-directory: ios 

      - name: Install Fastlane
        run: bundle exec fastlane --version
        working-directory: ios

      - name: Run tests
        run: bundle exec fastlane test
        working-directory: ios
