name: iOS Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: macos-setup-action@v2
        with:
          xcode-version: '14.2' 

      # - name: Cache Bundler dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bundler-

      # - name: Cache DerivedData
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/Library/Developer/Xcode/DerivedData
      #     key: ${{ runner.os }}-deriveddata-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-deriveddata-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0  # Версия Ruby, которую использует Fastlane

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Fastlane
        run: bundle exec fastlane --version

      - name: Run unit tests without simulator
        run: bundle exec fastlane test

